setup:
  mode: random
  ilp_solver:
    timeLimit: 60
    gapRel: 0.05
    objective: multi-objective # can be single-objective or multi-objective
    weights:
      latency: 1.0
      migration: 100.0
      server_usage: 50.0  # Tolerancia relativa para el óptimo (ej: 0.05 = 5%). Evita time-outs en modos complejos o en modo monolithic.

trigger_policy:
  type: solve_all
  # Ejemplo de politica periodica (solve_every_t_seconds)
  # interval_seconds: 10.0
  # Ejemplo de politica combinada:
  # type: combined
  # critical_events: ["disable_node", "disable_edge", "update_app_footprint", "update_app_network", "update_app_topology", "surge_popularity"]
  # interval_seconds: 10.0

infrastructure:
  num_nodes: 50
  model:
    name: scale_free
    m: 2
    layer:
      mode: centrality_based_layer
      thresholds:
        cloud_min: 0.1
        fog_min: 0.02


  node:
    actions:
      disable_node:
        frequency:
          type: uniform
          low: 0
          high: 300
        impact:
          distribution_to_enable_node:
            type: uniform
            low: 0
            high: 100
      degrade_node:
        frequency:
          type: exponential
          scale: 150
        impact:
          target_attributes: ["ram", "cpu"]
          p_loss_dist:
            type: beta
            a: 2
            b: 5
          distribution_to_restore_node:
            type: exponential
            scale: 50
    attributes:
      ram:
        mode: centrality_based
        centrality_type: direct_proportional
        distribution:
          type: pareto
          a: 1.16
        min: 8.0
        max: 16.0
        cloud:
          distribution:
            type: uniform
            low: 100000.0
            high: 100000.0
  edge:
    actions:
      disable_edge:
        frequency:
          type: uniform
          low: 0
          high: 300
        impact:
          distribution_to_enable_edge:
            type: uniform
            low: 0
            high: 100
      congest_edge:
        frequency:
          type: exponential
          scale: 60
        impact:
          target_attributes_loss: ["bandwidth"]
          target_attributes_multiplier: ["delay"]
          p_loss_dist:
            type: beta
            a: 2
            b: 5
          multiplier_dist:
            type: lognormal
            mean: 0.5
            sigma: 0.2
          distribution_to_clear_edge:
            type: exponential
            scale: 30
    attributes:
      delay:
        mode: homogenic
        distribution:
          type: uniform
          low: 0.1
          high: 5.0
app:
  num_apps: 20
  architecture: monolithic
  services:
    network:
      delay:
        distribution:
          type: uniform
          low: 10.0
          high: 50.0
      bandwidth:
        distribution:
          type: uniform
          low: 10.0
          high: 100.0
    topology_model: directed_scale_free # Puede ser 'sfc' o 'directed_scale_free'
    scale_free_settings:
      initial_nodes: 2
      edges_per_node: 2
    length_range: [2, 6]
    profiles:
      iot:
        prob: 0.6
        attributes:
          cpu:
            distribution:
              type: lognormal
              mean: 0.1
              sigma: 0.5
          ram:
            distribution:
              type: lognormal
              mean: 0.1
              sigma: 0.5
      video:
        prob: 0.4
        attributes:
          cpu:
            distribution:
              type: lognormal
              mean: 2.0
              sigma: 1.0
          ram:
            distribution:
              type: lognormal
              mean: 3.0
              sigma: 1.5
  popularity:
    distribution:
      type: zipf
      a: 1.2
    local_app_ratio: 0.3
    local_radius_influence: 0.15
  num_new_users:
    type: integers
    low: 1
    high: 6
  actions:
    remove_app:
      frequency:
        type: uniform
        low: 0
        high: 300
    update_app_footprint:
      frequency:
        type: exponential
        scale: 100
      impact:
        sigma_footprint:
          type: uniform
          low: 0.05
          high: 0.15
    update_app_network:
      frequency:
        type: exponential
        scale: 150
      impact:
        sigma_net:
          type: uniform
          low: 0.05
          high: 0.15
    update_app_topology:
      frequency:
        type: exponential
        scale: 120
      impact:
        l_min:
          type: integers
          low: 2
          high: 3
        l_max_global:
          type: integers
          low: 6
          high: 7
    surge_popularity:
      frequency:
        type: exponential
        scale: 200
      impact:
        transient_prob:
          type: uniform
          low: 0.7
          high: 0.7
        duration_dist:
          type: weibull
          a: 1.5
          scale: 10.0
    drop_popularity:
      frequency:
        type: exponential
        scale: 200
      impact:
        transient_prob:
          type: uniform
          low: 0.7
          high: 0.7
        duration_dist:
          type: weibull
          a: 1.5
          scale: 10.0
    geo_demand_shift:
      frequency:
        type: exponential
        scale: 50
      impact:
        jump_prob:
          type: uniform
          low: 0.2
          high: 0.2
        drift_dist:
          type: normal
          mean: 0.0
          sigma: 0.05

user:
  num_users: 2
  spatial_distribution:
    model: thomas_cluster
    hotspots: 5
    spread: 0.05
  spatial_region:
    width: 2.0
    height: 2.0
    num_vertical_streets: 10
    num_horizontal_streets: 10
  mobility:
    model: random
    turn_probabilities:
      straight: 0.33
      left: 0.33
      right: 0.34
    speed:
      type: uniform
      low: 0.005
      high: 0.02
    coverage_radius:
      type: normal
      mean: 0.2
      sigma: 0.02
  request_ratio:
    type: exponential
    scale: 5

  actions:
    remove_user:
      frequency:
        type: exponential
        scale: 300
    suspend_user:
      frequency:
        type: exponential
        scale: 150
      impact:
        resume_user:
          type: lognormal
          mean: 1.0
          sigma: 0.5
    move_user:
      frequency:
        type: exponential
        scale: 120
    change_request_ratio:
      frequency:
        type: exponential
        scale: 90
      impact:
        increase_probability: 0.5
        multiplier:
          type: uniform
          low: 1.5
          high: 3.0
        restore_ratio:
          type: lognormal
          mean: 1.0
          sigma: 0.5
global_spawner:
  actions:
    new_user:
      type_object: user
      action_type: new_user
      frequency:
        type: exponential
        scale: 30
    new_app:
      type_object: app
      action_type: new_app
      frequency:
        type: exponential
        scale: 3600  # Valor muy alto (1 hora en simulacion) para generar apps muy rara vez
