setup:
  mode: random
  num_nodes: 10
  graph_model: 'barabasi_albert' 

model_params:
  m: 2

attributes:
  graph:
    actions:
      disable_random_node:
        distribution: 'rng.uniform(0, 300)'
        action_params: 
          event_set: None
          distribution_to_enable_node: 'rng.uniform(0, 100)'
          sim_set: None
      
      disable_random_edge:
        distribution: 'rng.uniform(0, 300)'
        action_params: 
          event_set: None
          distribution_to_enable_edge: 'rng.uniform(0, 100)'
          sim_set: None
          
    node:
      ram: 'rng.pareto(1.16, {num_nodes})'
      min_ram: 8.0
      max_ram: 16.0

    edge:
      delay: 'rng.uniform(0.1, 5.0)'
  
  app:
    num_apps: 20
    saturation_percentage: 80
    popularity: 'rng.uniform(0.1, 1.0)'
    cpu: 'rng.uniform(0.1, 4.0)'
    ram: 'rng.uniform(4.0, 4.5)'
    disk: 'rng.uniform(10, 100)'
    time: 'rng.uniform(0, 300)'
    num_new_users: 'rng.integers(1, 6)'
    actions: 
      remove_app:
        distribution: 'rng.uniform(0, 300)'
        action_params: 
          user_set: None
          event_set: None
      increase_popularity:
        distribution: 'rng.uniform(0, 300)'
        action_params:
          multiplier: 'rng.uniform(1, 3)'
          user_set: None
          sim_set: None
      decrease_popularity: 
        distribution: 'rng.uniform(0, 300)'
        action_params:
          multiplier: 'rng.uniform(0, 1)'
          user_set: None
          sim_set: None
    
  user:
    num_users: 2
    request_ratio: 'rng.exponential(5)'
    request_popularity: 'rng.uniform(0.1, 1.0)'
    centrality: 'rng.uniform(0.1, 1.0)'
    actions:
      remove_user:
        distribution: 'rng.exponential(300)' # Users stay for 120 time units on average
        action_params:
          event_set: None
      move_user:
        distribution: 'rng.exponential(120)'
        action_params: 
          infrastructure: None
          sim_set: None
      increase_request_ratio:
        distribution: 'rng.exponential(90)'
        action_params:
          multiplier: 'rng.uniform(1, 3)'
          sim_set: None
      decrease_request_ratio: 
        distribution: 'rng.exponential(90)'
        action_params:
          multiplier: 'rng.uniform(0.2, 1)'
          sim_set: None

  new_object:
    new_user: 
      distribution: 'rng.exponential(30)' # A new user appears every 4 time units on average
      action_params:
        config: None
        app_set: None
        user_set: None
        infrastructure: None
        event_set: None
        sim_set: None

    # new_app: 
    #   distribution: 'rng.exponential(50)'
    #   action_params:
    #     config: None
    #     app_set: None
    #     user_set: None
    #     infrastructure: None
    #     event_set: None
    #     # Numpy equivalent for random integer between 1 and 5 (inclusive)
    #     num_new_users: 'rng.integers(1, 6)'
    #     sim_set: None