# General defaults
DEFAULT_SCENARIO_CONFIG_FILE = "scenario_config.yaml"
DEFAULT_SOLVER_CONFIG_FILE = "solver_config.yaml"
DEFAULT_MASTER_SEED = 42
DEFAULT_TOTAL_ITERATIONS = 500

# Infrastructure constants
DEFAULT_INFRA_ID = "000"
DEFAULT_NUM_NODES = 10
DEFAULT_MIN_RAM = 8
DEFAULT_MAX_RAM = 16
DEFAULT_TREE_BRANCHING_R = 2
DEFAULT_TREE_BRANCHING_H = 3

# Optimization constants
INFEASIBLE_PENALTY = 1_000_000
PENALTY_DELAY = INFEASIBLE_PENALTY

