# General defaults
DEFAULT_CONFIG_FILE = "config_random.yaml"
DEFAULT_MASTER_SEED = 42
DEFAULT_TOTAL_ITERATIONS = 500

# Infrastructure constants
DEFAULT_INFRA_ID = "000"
DEFAULT_NUM_NODES = 10
DEFAULT_MIN_RAM = 8
DEFAULT_MAX_RAM = 16
DEFAULT_TREE_BRANCHING_R = 2
DEFAULT_TREE_BRANCHING_H = 3

# Optimization constants
PENALTY_DELAY = 1_000_000
